--- #YAML:1.0
name: Test-Distribution
version: 1.13
author:
  - ~
abstract: perform tests on all modules of a distribution
license: perl
requires:
  File::Find::Rule: 0.03
  Module::CoreList: 1.93
  Test::More: 0.45
  Test::Pod: 0.95
  Test::Signature: 0
provides:
  Test::Distribution:
    file: lib/Test/Distribution.pm
    version: 1.13
  Test::Distribution::base:
    file: lib/Test/Distribution.pm
    version: 1.13
  Test::Distribution::description:
    file: lib/Test/Distribution.pm
    version: 1.13
  Test::Distribution::exports:
    file: lib/Test/Distribution.pm
    version: 1.13
  Test::Distribution::manifest:
    file: lib/Test/Distribution.pm
    version: 1.13
  Test::Distribution::pod:
    file: lib/Test/Distribution.pm
    version: 1.13
  Test::Distribution::prereq:
    file: lib/Test/Distribution.pm
    version: 1.13
  Test::Distribution::sig:
    file: lib/Test/Distribution.pm
    version: 1.13
  Test::Distribution::use:
    file: lib/Test/Distribution.pm
    version: 1.13
  Test::Distribution::versions:
    file: lib/Test/Distribution.pm
    version: 1.13
generated_by: Module::Build version 0.24
